config/routes.rb
Rails.application.routes.draw do
  resources :aulas
  resources :pessoas
  resources :disciplinas
  resources :cursos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :disciplina

  validates :ata, :objetivo, :data, :titulo, :duracao, presence: true
  validates :duracao, numericality: { only_integer: true,
                                      greater_than_or_equal_to: 40 }
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: [:show, :edit, :update, :destroy]

  # GET /aulas
  # GET /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1
  # GET /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas
  # POST /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: 'Aula was successfully created.' }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1
  # PATCH/PUT /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: 'Aula was successfully updated.' }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1
  # DELETE /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: 'Aula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_params
      params.require(:aula).permit(:disciplina_id, :data, :duracao, :titulo, :objetivo, :ata)
    end
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/views/aulas/_form.html.erb
<%= form_with(model: aula, local: true) do |form| %>
  <% if aula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aula.errors.count, "error") %> prohibited this aula from being saved:</h2>

      <ul>
      <% aula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :disciplina_id %>
    <%= form.text_field :disciplina_id %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :duracao %>
    <%= form.number_field :duracao %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :objetivo %>
    <%= form.text_area :objetivo %>
  </div>

  <div class="field">
    <%= form.label :ata %>
    <%= form.text_area :ata %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aulas/edit.html.erb
<h1>Editing Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Show', @aula %> |
<%= link_to 'Back', aulas_path %>

app/views/aulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aulas</h1>

<table>
  <thead>
    <tr>
      <th>Disciplina</th>
      <th>Data</th>
      <th>Duracao</th>
      <th>Titulo</th>
      <th>Objetivo</th>
      <th>Ata</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aulas.each do |aula| %>
      <tr>
        <td><%= aula.disciplina %></td>
        <td><%= aula.data %></td>
        <td><%= aula.duracao %></td>
        <td><%= aula.titulo %></td>
        <td><%= aula.objetivo %></td>
        <td><%= aula.ata %></td>
        <td><%= link_to 'Show', aula %></td>
        <td><%= link_to 'Edit', edit_aula_path(aula) %></td>
        <td><%= link_to 'Destroy', aula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aula', new_aula_path %>

app/views/aulas/new.html.erb
<h1>New Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Back', aulas_path %>

app/views/aulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Disciplina:</strong>
  <%= @aula.disciplina %>
</p>

<p>
  <strong>Data:</strong>
  <%= @aula.data %>
</p>

<p>
  <strong>Duracao:</strong>
  <%= @aula.duracao %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @aula.titulo %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @aula.objetivo %>
</p>

<p>
  <strong>Ata:</strong>
  <%= @aula.ata %>
</p>

<%= link_to 'Edit', edit_aula_path(@aula) %> |
<%= link_to 'Back', aulas_path %>